# Generated by Django 6.0.5 on 2026-05-22 10:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name="Date d'entrée")),
                ('date_fin', models.DateField(verbose_name='Date de sortie')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('archivee', 'Archivée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de demande')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('date_visite', models.DateField(blank=True, null=True, verbose_name='Date de visite prévue')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='logements.chambre', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_demande'],
            },
        ),
    ]
