# Generated by Django 6.0.5 on 2026-06-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='heure_visite',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de la visite'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu_visite',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lieu de la visite'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_visite',
            field=models.DateField(blank=True, null=True, verbose_name='Date de visite choisie'),
        ),
    ]
