# Generated by Django 6.0.5 on 2026-05-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avis', '0001_initial'),
        ('logements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='logements.chambre', verbose_name='Chambre'),
        ),
    ]
