# Generated by Django 6.0.5 on 2026-05-22 10:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('photos', 'Photos incorrectes'), ('prix', 'Prix trompeur'), ('inexistante', 'Chambre inexistante'), ('etat', 'Mauvais état'), ('autre', 'Autre')], max_length=20, verbose_name='Motif')),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('cloture', 'Clôturé')], default='ouvert', max_length=20, verbose_name='Statut')),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du signalement')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='logements.chambre', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
