# Generated by Django 6.0.5 on 2026-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilproprietaire',
            name='numero_piece',
        ),
        migrations.AddField(
            model_name='profilproprietaire',
            name='piece_identite_recto',
            field=models.ImageField(blank=True, upload_to='pieces_identite/recto/', verbose_name="Recto pièce d'identité"),
        ),
        migrations.AddField(
            model_name='profilproprietaire',
            name='piece_identite_verso',
            field=models.ImageField(blank=True, upload_to='pieces_identite/verso/', verbose_name="Verso pièce d'identité"),
        ),
    ]
