# Generated by Django 6.0.5 on 2026-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_expediteur', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('objet_message', models.CharField(max_length=255, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
                ('reponse_admin', models.TextField(blank=True, verbose_name='Réponse')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
