# Generated by Django 6.0.5 on 2026-05-22 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('superficie', models.PositiveIntegerField(verbose_name='Superficie (m²)')),
                ('loyer', models.PositiveIntegerField(verbose_name='Loyer mensuel (FCFA)')),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('studio', 'Studio'), ('appartement', 'Appartement')], default='simple', max_length=20, verbose_name='Type')),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('renovation', 'En rénovation')], default='bon', max_length=20, verbose_name='État')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('meublee', models.BooleanField(default=False, verbose_name='Meublée')),
                ('wc_interieur', models.BooleanField(default=False, verbose_name='WC intérieur')),
                ('cuisine', models.BooleanField(default=False, verbose_name='Cuisine')),
                ('internet', models.BooleanField(default=False, verbose_name='Internet')),
                ('eau_courante', models.BooleanField(default=True, verbose_name='Eau courante')),
                ('electricite', models.BooleanField(default=True, verbose_name='Électricité')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cité',
                'verbose_name_plural': 'Cités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chambres/%Y/%m/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-est_principale', 'date_upload'],
            },
        ),
        migrations.CreateModel(
            name='PhotoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chambres/%Y/%m/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-est_principale', 'date_upload'],
            },
        ),
    ]
