# Generated by Django 6.0.5 on 2026-05-19 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('superficie', models.PositiveIntegerField(help_text='En m²')),
                ('loyer', models.PositiveIntegerField(help_text='En FCFA par mois')),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('studio', 'Studio'), ('appartement', 'Appartement')], default='simple', max_length=20)),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('renovation', 'En rénovation')], default='bon', max_length=20)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('meublee', models.BooleanField(default=False)),
                ('salle_de_bain', models.BooleanField(default=False)),
                ('cuisine', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('eau_courante', models.BooleanField(default=True)),
                ('electricite', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cité',
                'verbose_name_plural': 'Cités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='chambres/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('est_principale', models.BooleanField(default=False)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-est_principale', 'date_upload'],
            },
        ),
    ]
