# Generated by Django 6.0.5 on 2026-05-19 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='proprietaire',
            field=models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='cites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chambre',
            name='cite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='logements.cite'),
        ),
        migrations.AddField(
            model_name='photo',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='logements.chambre'),
        ),
    ]
