# Generated by Django 6.0.5 on 2026-05-25 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocity',
            options={'ordering': ['-est_principale', 'date_upload'], 'verbose_name': 'Photo Cité', 'verbose_name_plural': 'Photos Cités'},
        ),
        migrations.AlterField(
            model_name='photocity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_cite', to='logements.cite', verbose_name='Cite'),
        ),
        migrations.AlterField(
            model_name='photocity',
            name='image',
            field=models.ImageField(upload_to='cites/%Y/%m/', verbose_name='Image'),
        ),
    ]
