# Generated by Django 6.0.5 on 2026-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0003_alter_photocity_options_alter_photocity_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Visible sur le site'),
        ),
        migrations.AddField(
            model_name='cite',
            name='motif_suppression',
            field=models.TextField(blank=True, verbose_name='Raison de la suppression/rejet'),
        ),
    ]
