# Generated by Django 6.0.5 on 2026-05-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0004_cite_est_actif_cite_motif_suppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Visible sur le site'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='motif_suppression',
            field=models.TextField(blank=True, help_text="Expliquez ici au propriétaire pourquoi sa chambre n'est plus visible.", verbose_name='Raison de la désactivation/suppression'),
        ),
    ]
