# Generated by Django 6.0.5 on 2026-05-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0005_chambre_est_actif_chambre_motif_suppression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cite',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cite',
            name='longitude',
        ),
        migrations.AddField(
            model_name='chambre',
            name='armoire',
            field=models.BooleanField(default=False, verbose_name='Armoire'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('moderne', 'Moderne'), ('studio', 'Studio'), ('appartement', 'Appartement')], default='simple', max_length=20, verbose_name='Type'),
        ),
    ]
