# Generated by Django 6.0.5 on 2026-06-03 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0006_remove_cite_latitude_remove_cite_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateVisiteChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de visite disponible')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_visite', to='logements.chambre', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Date de visite',
                'verbose_name_plural': 'Dates de visite',
                'ordering': ['date'],
                'unique_together': {('chambre', 'date')},
            },
        ),
    ]
